TileDB-Inc/TileDB-CSharp

- TileDB.CSharp/src/AttributeError.cs
- TileDB.CSharp/src/SchemaMismatch.cs
- TileDB.CSharp/src/TileDBError.cs
- TileDB.CSharp/src/TypeError.cs
- cpp/src/tiledb_csharp_cpp_wrapper.cxx
- cpp/src/tiledb_csharp_cpp_wrapper_linux64.cxx
- cpp/swig/swig_tiledb_exception.i
All we need is the exception type and error string, so remove the SWIG
class boilerplate for the exception classes. Now the error message is
passed through from libtiledb.
before: `Exception of type 'TileDB.TypeError' was thrown.`
after: `TileDB.TypeError: Static type (INT32) does not match expected
type (UINT64)`
> Fix ch9553 ch9667 exception order and error message handling

- TileDB.CSharp/src/Query.cs
- TileDB.CSharp/src/TileDBBuffer.cs
- TileDB.CSharp/src/tiledbcsPINVOKE.cs
- cpp/src/tiledb/cxx_api/tiledb_cxx_query.h
- cpp/src/tiledb_csharp_cpp_wrapper.cxx
- cpp/src/tiledb_csharp_cpp_wrapper_linux64.cxx
- examples/ExampleTileDBBufferString.cs
- examples/TileDB.Example/TileDB.Example.csproj
This PR adds PackStringBuffer and UnPackStringBuffer functions in class TileDBBuffer. The end users don't need to handle offsets.
> Pack and UnPack string buffer

- cpp/src/CMakeLists.txt
This let me build a nuget package on mac with the release bundle.
> Install runtime artifacts for TileDB target (eg for use in packaging)

- .github/workflows/tiledb-csharp.yml
With these CI changes a TileDB-CSharp release can be triggered by pushing a new tag. After passing initial tests and building an updated NuGet package for this release, the workflow will upload `TileDB.CSharp.*.nupkg` as an artifact and later jobs will download this artifact to test the NuGet package locally on Windows, Mac, and Linux.
Any push to `main` will result in this workflow being triggered, but the final `Release` job will not run without a release tag. Always open to thoughts or suggestions on how this could be improved. 
Triggered this workflow manually (with no release tag): https://github.com/TileDB-Inc/TileDB-CSharp/actions/runs/2693214014
> Add CI for triggering releases

- .github/workflows/nightly-issue-template.md
- .github/workflows/nightly.yml
Nightly builds against TileDB `release-2.10`, `release-2.11`, and `dev`, similar to nightly CI for TileDB-Py / TileDB-R. 
Schedule is currently set to 2:15AM UTC / 10:15PM ET and failed builds will create an issue assigned to me.
> CI for nightly builds

- examples/TileDB.CSharp.Example/TileDB.CSharp.Example.csproj
- scripts/generate/README.md
- sources/TileDB.CSharp/TileDB.CSharp.csproj
- sources/TileDB.CSharp/TileDB.CSharp.targets
- sources/TileDB.Interop/LibDllImport.cs
- sources/TileDB.Interop/Methods.ResolveLibrary.cs
- sources/TileDB.Interop/Methods.cs
- sources/TileDB.Interop/TileDB.Interop.csproj
- tests/TileDB.CSharp.Test/TileDB.CSharp.Test.csproj
Relocated `LibDllImport.cs` as an extension of `Methods.cs` to ensure DllImport resolver is registered. Generating bindings doesn't require any edits to `Methods.cs` using the following command (aside from commenting out `*_dump` functions). Updated `scripts/generate/README.md` to reflect these changes.
```bash
~/.dotnet/tools/ClangSharpPInvokeGenerator -I /usr/local/lib/include/ -I ~/Code/Clones/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/clang/14.0.0/include/ --file /usr/local/include/tiledb/tiledb.h /usr/local/include/tiledb/tiledb_experimental.h @scripts/generate/generate.rsp -l libtiledb
```
Included a resolver for libc, but it doesn't look like libc is currently in use. I still put this in place to if / when we need it, and It also serves as an example of how we can extend …
> Add DllImport resolver

- .github/workflows/nightly.yml
- .github/workflows/tiledb-csharp.yml
- examples/bindings/quickstart_sparse_string/quickstart_sparse_string.csproj
This will run all current and future example projects stored under the `examples/` subdirectory. Alternatively we could itemize them, just thought it might be nice if the CI could pick up new examples without needing updated.
> Run examples using CI

- .github/workflows/nightly.yml
- .github/workflows/tiledb-csharp.yml
- examples/TileDB.CSharp.Example/TileDB.CSharp.Example.csproj
- examples/bindings/quickstart_sparse_string/quickstart_sparse_string.csproj
- sources/TileDB.CSharp/TileDB.CSharp.csproj
- sources/TileDB.Interop/TileDB.Interop.csproj
- tests/TileDB.CSharp.Test/TileDB.CSharp.Test.csproj
Added `RollForward` tag to msbuild configurations to use .NET 6 if available. If both .NET 5.0 and .NET 6.0 SDKs are available and we use `dotnet run` without an explicit `--framework net5.0` .NET 6.0 will be used. The `--framework` flag should only be set if .NET 5.0 and 6.0 SDKs are both available and we want to target .NET 5.0. 
CI now tests building with both .NET 5.0 and 6.0 using new msbuild configurations. I used docker to test building in environments limited to either .NET 5.0 *or* .NET 6.0.
```bash
docker run -v $(pwd):/app -w /app/examples/TileDB.CSharp.Example mcr.microsoft.com/dotnet/sdk:6.0 dotnet run
docker run -v $(pwd):/app -w /app/examples/TileDB.CSharp.Example mcr.microsoft.com/dotnet/sdk:5.0 dotnet run
```
> Add CI for .NET 6.0

- Directory.Build.props
To be automatically imported by `MSBuild`, the property file has to be named `Directory.Build.props` instead of `Default.Build.props`. I fixed it, and also updated the analyzer to its latest version.
> Fix `SonarAnalyzer.CSharp` not running.

- .config/dotnet-tools.json
- scripts/generate/README.md
- scripts/generate/generate.rsp
- sources/TileDB.CSharp/File.cs
- sources/TileDB.Interop/InteropAux.cs
- sources/TileDB.Interop/Methods.cs
- sources/TileDB.Interop/MethodsExperimental.cs
- sources/TileDB.Interop/tiledb_array_type_t.cs
- sources/TileDB.Interop/tiledb_datatype_t.cs
- sources/TileDB.Interop/tiledb_encryption_type_t.cs
- sources/TileDB.Interop/tiledb_experimental_query_status_details_t.cs
- sources/TileDB.Interop/tiledb_filesystem_t.cs
- sources/TileDB.Interop/tiledb_filter_option_t.cs
- sources/TileDB.Interop/tiledb_filter_type_t.cs
- sources/TileDB.Interop/tiledb_layout_t.cs
- sources/TileDB.Interop/tiledb_mime_type_t.cs
- sources/TileDB.Interop/tiledb_object_t.cs
- sources/TileDB.Interop/tiledb_query_condition_combination_op_t.cs
- sources/TileDB.Interop/tiledb_query_condition_op_t.cs
- sources/TileDB.Interop/tiledb_query_status_details_reason_t.cs
- sources/TileDB.Interop/tiledb_query_status_t.cs
- sources/TileDB.Interop/tiledb_query_type_t.cs
- sources/TileDB.Interop/tiledb_vfs_mode_t.cs
- sources/TileDB.Interop/tiledb_walk_order_t.cs
The bindings generation process has been streamlined in the following ways:
* `ClangSharpPInvokeGenerator` is installed as a local tool, ensuring we are in a common version. It was also updated to its latest one.
* Additional arguments have been passed to the generator such that we no longer need to manually edit `Methods.cs` afterwards. These arguments were also placed in `generate.rsp`.
* After these changes, the bindings were regenerated, with some breaking changes. I can't explain them, they also manifested with version 13.0.0-beta1 of the generator. But the previous versions were wrong. `size_t` maps to `nuint` in C# and not `ulong`, and nothing implied that enums are unsigned.
> Improve the bindings generation process and regenerate them.

- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/ArraySchema.cs
- sources/TileDB.CSharp/Attribute.cs
- sources/TileDB.CSharp/Dimension.cs
- sources/TileDB.CSharp/Domain.cs
- sources/TileDB.CSharp/File.cs
- sources/TileDB.CSharp/FilterList.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ArrayHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ArraySchemaEvolutionHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ArraySchemaHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/AttributeHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ConfigHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ConfigIteratorHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ContextHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/DimensionHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/DomainHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/FilterHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/FilterListHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/GroupHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/QueryConditionHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/QueryHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/VFSHandle.cs
- sources/TileDB.CSharp/QueryCondition.cs
A continuation of #106, this PR removes the `CreateUnowned` function from the safe handles and creates them as owned, according to the usual pattern. Unowned handles were never released from native code, even if we call `Dispose()`, resulting in leaks. These leaks should be patched.
> Always create owned safe handles.

- .github/workflows/nightly.yml
- tests/TileDB.CSharp.Test/FilterTest.cs
Nightly builds on 2.11 are failing because the `tiledb_status_code` function does not exist. This PR modifies `nightly.yml` to stop testing on 2.11.
Fixes #134 #135 #136 #140 #142. See [SC-23174](https://app.shortcut.com/tiledb-inc/story/23174/reconsider-testing-with-older-core-versions).
> Stop testing 2.11 on nightly builds.

- sources/TileDB.CSharp/Enums.cs
- sources/TileDB.CSharp/FragmentInfo.cs
- sources/TileDB.CSharp/Marshalling/MarshaledStringOut.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/FragmentInfoHandle.cs
- sources/TileDB.CSharp/Marshalling/ScratchBuffer.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- tests/TileDB.CSharp.Test/FragmentInfoTest.cs
- tests/TileDB.CSharp.Test/TestUtil.cs
This PR implements TileDB's fragment info API, and adds tests to it, ported from Java.
[SC-22321](https://app.shortcut.com/tiledb-inc/story/22321/add-high-level-wrapper-for-fragmentinfo-api)
> Add `FragmentInfo`.

- sources/TileDB.CSharp/TileDB.CSharp.csproj
There is no reason for it to be different.
> Change the library's compiled output path to `bin`.

- .github/workflows/release.yml
- .github/workflows/tiledb-csharp.yml
This PR adds a workflow that runs when a tag gets pushed, packs `TileDB.CSharp` and pushes it to nuget.org. With that the release process gets fully automated, and produces [deterministic NuGet packages compatible with SourceLink](https://mitchelsellers.com/blog/article/net-5-deterministic-builds-source-linking).
Before merging it you have to create a [NuGet API key](https://www.nuget.org/account/apikeys) that can push new versions of `TileDB.CSharp` and add it as a [secret](https://github.com/TileDB-Inc/TileDB-CSharp/settings/secrets/actions) with the name `TILEDB_CSHARP_NUGET_KEY`.
> Add a Release workflow.

- sources/TileDB.CSharp/GroupMetadata.cs
We were calling `tiledb_array_consolidate_metadata` by mistake.
> Fix typo in `Group.ConsolidateMetadata`.

- sources/TileDB.CSharp/Context.cs
Calling `Context.GetDefault()` from multiple threads may create multiple `Context`s. This PR ensures only one will be created. Calling `Dispose()` on this default context will now do nothing (previously it was prone to causing subsequent operations to fail).
I also better documented the `Context` class.
> Ensure the default `Context` is created only once and don't dispose it.

- Directory.Build.props
- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/FragmentInfo.cs
- sources/TileDB.CSharp/Marshalling/MarshaledString.cs
- sources/TileDB.CSharp/Marshalling/MarshaledStringCollection.cs
- sources/TileDB.CSharp/Marshalling/SafeHandleHolder.cs
- tests/TileDB.CSharp.Test/ArrayTest.cs
[SC-22323](https://app.shortcut.com/tiledb-inc/story/22323/build-staged-consolidation-example-and-tests)
I also tidied up the `Array.Consolidate` and `Vacuum` methods.
~~TODO: write tests.~~
> Add support for fragment consolidation.

- Directory.Packages.props
- sources/TileDB.CSharp/TileDB.CSharp.csproj
We add a `LocalLibraryFile` property that if set, it will just copy the native file to the output directory, without using the native NuGet packages mechanism.
Tested locally on a Windows machine and works.
c.c. @ihnorton who had asked for it.
> Simplify testing with custom native binaries.

- docs/obsoletions.md
- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/Config.cs
- sources/TileDB.CSharp/ConfigIterator.cs
- sources/TileDB.CSharp/Context.cs
- sources/TileDB.CSharp/Error.cs
- sources/TileDB.CSharp/ErrorHandling.cs
- sources/TileDB.CSharp/FilterList.cs
- sources/TileDB.CSharp/Obsoletions.cs
- sources/TileDB.CSharp/TileDBException.cs
- tests/TileDB.CSharp.Test/ArraySchemaTest.cs
- tests/TileDB.CSharp.Test/DomainTest.cs
- tests/TileDB.CSharp.Test/GroupTest.cs
Until now, when a native API call fails, we throw a plain `Exception`, giving little ways for consumers to distinguish between TileDB errors and anything else.
This PR introduces a new exception type called `TileDBException` that gets thrown when a native API call fails, and corresponds to the `TileDBError` type that C++, Python and Java have. Since we throw a more derived type of exception, [this is not a breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/#exceptions).
I also made the `Context.ErrorHappened` ~~event useful; as explained in [SC-23974](https://app.shortcut.com/tiledb-inc/story/23974/context-errorhappened-is-useless), the default value we give to it throws and prevents user-supplied events to be invoked. We might want to just~~ obsolete and ignore …
> Add `TileDBException` and obsolete `Context.ErrorHappened` and `ErrorException`.

- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/ArraySchema.cs
- sources/TileDB.CSharp/Attribute.cs
- sources/TileDB.CSharp/Dimension.cs
- sources/TileDB.CSharp/Domain.cs
- sources/TileDB.CSharp/File.cs
- sources/TileDB.CSharp/FilterList.cs
- sources/TileDB.CSharp/FragmentInfo.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ArrayHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ArraySchemaEvolutionHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ArraySchemaHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/AttributeHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ConfigHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ConfigIteratorHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ContextHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/DimensionHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/DomainHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/FilterHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/FilterListHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/FragmentInfoHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/GroupHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/QueryConditionHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/QueryHandle.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/VFSHandle.cs
- sources/TileDB.CSharp/QueryCondition.cs
This will allow the GC to skip finalization and collect them sooner.
> Invalidate safe handles that failed to be created.

- .editorconfig
- sources/TileDB.CSharp/Context.cs
- sources/TileDB.CSharp/Enums.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/VFSFileHandle.cs
- sources/TileDB.CSharp/VFS.cs
- sources/TileDB.CSharp/VFSFile.cs
- tests/TileDB.CSharp.Test/ContextTest.cs
- tests/TileDB.CSharp.Test/VFSTest.cs
[SC-24114](https://app.shortcut.com/tiledb-inc/story/24114/expose-all-vfs-functions-in-c)
> Clean-up the `VFS` class and expose the remaining VFS APIs.

- .editorconfig
- docs/obsoletions.md
- examples/TileDB.CSharp.Example/ExampleIncompleteQuery.cs
- examples/TileDB.CSharp.Example/ExampleQuery.cs
- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/ArrayMetadata.cs
- sources/TileDB.CSharp/Attribute.cs
- sources/TileDB.CSharp/Dimension.cs
- sources/TileDB.CSharp/ErrorHandling.cs
- sources/TileDB.CSharp/File.cs
- sources/TileDB.CSharp/Filter.cs
- sources/TileDB.CSharp/FragmentInfo.cs
- sources/TileDB.CSharp/GroupMetadata.cs
- sources/TileDB.CSharp/Marshalling/ScratchBuffer.cs
- sources/TileDB.CSharp/Marshalling/SequentialPair.cs
- sources/TileDB.CSharp/Obsoletions.cs
- sources/TileDB.CSharp/QueryCondition.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- tests/TileDB.CSharp.Test/ArrayMetadataTest.cs
- tests/TileDB.CSharp.Test/ArraySchemaEvolutionTest.cs
- tests/TileDB.CSharp.Test/ArraySchemaTest.cs
- tests/TileDB.CSharp.Test/ArrayTest.cs
- tests/TileDB.CSharp.Test/AttributeTest.cs
- tests/TileDB.CSharp.Test/DimensionTest.cs
- tests/TileDB.CSharp.Test/GroupTest.cs
- tests/TileDB.CSharp.Test/QueryConditionTest.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
This PR removes most uses of `GCHandle`s and replaces them with directly using pointers when passing values on the stack to native code, or with the `fixed` statement when pinning values on the heap.
The remaining uses of `GCHandle`s are in the bindings example (that will eventually be removed), the deprecated `TileDBBuffer` class, the soon-to-be-deprecated subarray methods on `Query`, and the long-term pinning of query buffers and keeping alive the `Query` for the duration of an async submit (the only valid use casees).
I also took the opportunity to clean-up the files I touched and deprecate the `Dimension.Create` overload that takes an array; only the first two values are actually used; the overload that explicitly takes the lower and upper bounds better represents the method's intent. …
> Do not use `GCHandle`s for brief pinning of objects.

- docs/obsoletions.md
- sources/TileDB.CSharp/Obsoletions.cs
- sources/TileDB.CSharp/QueryCondition.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- tests/TileDB.CSharp.Test/QueryConditionTest.cs
This PR introduces the `&`, `|` and `!` operators for `QueryConditions` that replace the `Combine` method which was marked as obsolete. I also obsoleted the constructor and `Init` method, in favor of the `Create` static factory.
[SC-24169](https://app.shortcut.com/tiledb-inc/story/24169/more-fluent-query-condition-combining)
> Clean-up the `QueryCondition` class, introduce combination operators et.al.

- sources/TileDB.CSharp/VFS.cs
- tests/TileDB.CSharp.Test/VFSTest.cs
I thought we needed a not-yet-released C# feature to make it generic, turns out we didn't.
The way it works is the following: the Core used to call `VisitCallback` which took a pointer to a structure containing the callback the user gave and an object argument to it. Now we get an extra level of indirection and `VisitCallback` calls another callback which is generic and calls the user callbacks. The reason for this is that `VisitCallback` itself cannot be made generic.
> Make `VFS.VisitChildren` generic.

- sources/TileDB.CSharp/Context.cs
- tests/TileDB.CSharp.Test/ContextTest.cs
- tests/TileDB.CSharp.Test/TemporaryDirectory.cs
TODO: Add tests.
[SC-24856](https://app.shortcut.com/tiledb-inc/story/24586/add-high-level-api-for-tiledb-object-type-and-related-functions)
> Expose the `tiledb_object_***` APIs.

- sources/TileDB.CSharp/Query.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
- tests/TileDB.CSharp.Test/TileDB.CSharp.Test.csproj
Apart from trivial clean-ups and fixes, the most important change in this PR is a refactoring of how the query buffers are managed.
Instead of `GCHandle` we use the newer `MemoryHandle` type which is more flexible and supports arbitrary pointers that might or might not be pinned. On top of that I added overloads to `Set***Buffer` that accept buffers from `Memory<T>` (a safe type that can repserent buffers like an array or part of an array). These overloads are essential for enabling user code to optimize performance and memory efficiency. I also changed the order of setting a buffer and unpinning the previous one to be more resilient to errors the Core might report.
[SC-24176](https://app.shortcut.com/tiledb-inc/story/24176/allow-query-buffers-from-more-sources)
> Optimize and clean-up the `Query` class, and support setting buffers from more sources.

- docs/obsoletions.md
- sources/TileDB.CSharp/Obsoletions.cs
I have manually tested that now clicking a link in an obsoletion message guides you to the right section of the document.
> Fix the obsoletion links.

- examples/TileDB.CSharp.Example/ExampleIncompleteQueryStringDimensions.cs
- sources/TileDB.CSharp/Query.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- tests/TileDB.CSharp.Test/DeletesTest.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
[SC-24679](https://app.shortcut.com/tiledb-inc/story/24679/add-high-performance-alternatives-to-query-resultbufferelements)
This PR adds four new `Query` APIs that get the number of elements written at a single buffer and for a single attribute/dimension at a time. Their advantage over `ResultBufferElements` is that they are much faster; they do not allocate, nor call into the Core to get the element size; it is kept when we set the buffers. If they are called with a name that does not exist, they throw.
This is the final API shape (differs from the story):
```csharp
public class Query
{
public ulong GetResultDataBytes(string name);
// It will throw if the data buffer had been set with UnsafeSetDataBuffer.
// Consumers can either keep using ResultBufferElements, or call …
```
> Add high-performance alternatives to `Query.ResultBufferElements`.

- tests/TileDB.CSharp.Test/ConfigTest.cs
`ConfigTest.ConfigGet` was renamed to `ConfigGetNonExistent`, and `ConfigUnset` was changed to not assume default values. Fixes #242.
> Improve robustness of config tests.

- .github/workflows/nightly.yml
- .github/workflows/tiledb-csharp.yml
I discovered some time ago that if we run `dotnet test` in a multi-targeting project without specifying the framework, the tests will automatically run on all frameworks. This cuts the number of CI jobs in half.
> Streamline testing from CI.

- sources/TileDB.CSharp/Context.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/ContextHandle.cs
I just learned what `tiledb_context_set_tag` does, and saw that the Core sets the tag to `c`. We set it to `csharp`.
> Set the `x-tiledb-api-language` tag when creating new contexts.

- sources/TileDB.CSharp/ArrayMetadata.cs
- sources/TileDB.CSharp/Attribute.cs
- sources/TileDB.CSharp/GroupMetadata.cs
- sources/TileDB.CSharp/Marshalling/MarshaledStringOut.cs
- tests/TileDB.CSharp.Test/ArrayMetadataTest.cs
> Improve string decoding; use UTF-8 by default.

- examples/TileDB.CSharp.Example/ExampleIncompleteQuery.cs
- examples/TileDB.CSharp.Example/ExampleIncompleteQueryStringDimensions.cs
- examples/TileDB.CSharp.Example/ExampleIncompleteQueryVariableSize.cs
- examples/TileDB.CSharp.Example/ExampleQuery.cs
- examples/TileDB.CSharp.Example/ExampleWritingDenseGlobal.cs
- examples/TileDB.CSharp.Example/ExampleWritingSparseGlobal.cs
- sources/TileDB.CSharp/Query.cs
- tests/TileDB.CSharp.Test/ArrayTest.cs
- tests/TileDB.CSharp.Test/AttributeTest.cs
- tests/TileDB.CSharp.Test/DeletesTest.cs
- tests/TileDB.CSharp.Test/FragmentInfoTest.cs
- tests/TileDB.CSharp.Test/IncompleteQueryTest.cs
- tests/TileDB.CSharp.Test/QueryConditionTest.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
- tests/TileDB.CSharp.Test/StatsTest.cs
- tests/TileDB.CSharp.Test/TestUtil.cs
They take the context of the array, like `Subarray`'s constructors, which never took a context. The existing constructors were hidden; it's not necessary to obsolete them.
> Add `Query` constructor overloads that do not take a `Context`.

- .github/workflows/tiledb-csharp.yml
- sources/TileDB.CSharp/FragmentInfo.cs
- sources/TileDB.CSharp/TileDB.CSharp.csproj
This PR uses [the .NET SDK's package validation feature](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview) to validate that `TileDB.CSharp` does not have any backwards-incompatible changes, compared to a published version of the package (currently 5.5.0). If we need to introduce a breaking change, we will have to [explicitly suppress the error](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview#suppress-compatibility-errors).
I created an additional CI job that runs `dotnet pack` which will trigger the analysis, and will test it by trying to introduce a breaking change in the PR.
> Enable package validation.

- sources/TileDB.CSharp/CoreUtil.cs
`CoreUtil.PackStringArray` can now use UTF-8.
> Fix typos.

- docs/obsoletions.md
- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/ArrayMetadata.cs
- sources/TileDB.CSharp/Attribute.cs
- sources/TileDB.CSharp/Dimension.cs
- sources/TileDB.CSharp/Enums.cs
- sources/TileDB.CSharp/ErrorHandling.cs
- sources/TileDB.CSharp/FragmentInfo.cs
- sources/TileDB.CSharp/GroupMetadata.cs
- sources/TileDB.CSharp/Interop/SpanExtensions.cs
- sources/TileDB.CSharp/Marshalling/MarshaledStringOut.cs
- sources/TileDB.CSharp/Obsoletions.cs
- sources/TileDB.CSharp/Query.cs
- sources/TileDB.CSharp/Subarray.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- sources/TileDB.CSharp/TileDB.CSharp.csproj
- tests/TileDB.CSharp.Test/FragmentInfoTest.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
[SC-24612](https://app.shortcut.com/tiledb-inc/story/26412/reconsider-the-rules-of-generic-type-validation)
The C# API's rules around type validation in its generic methods have some defects that prevent datetime types and non-ASCII strings from being used. This PR improves the type validation to fix these cases.
* When performing type validation, instead of converting the .NET `Type` to a TileDB `DataType` and compare them, we do the opposite. This happens because (with few exceptions), the mapping between .NET types and TileDB data types is one-to-many, and so by "narrowing down" we can validate that datetime data types match with `long`, while `long` maps to `DataType.Int64`.
* The validation logic was centralized in the `ErrorHandling.CheckDataType`. It accepts a generic type …
> Fix generic type validation to support datetimes and non-ASCII strings.

- sources/TileDB.CSharp/Query.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
The existing overloads of `Query.UnsafeSetDataBuffer` are memory-unsafe because they deal with raw pointers or their equivalents (`MemoryHandle`). This PR adds overloads that accept a `Memory<byte>` and `ReadOnlyMemory<byte>` (the latter for write queries only). They pin the buffers and pass them to the Core, without performing type validation.
> Add more overloads to set query data buffers without type validation.

- .github/dependabot.yml
- Directory.Packages.props
It likely won't fix the nightly build failures, as tested in the past, but it's still good to keep being updated nevertheless.
All dependencies being updated are used only for tests and infrastructure.
> Update dependencies and add a Dependabot file to weekly update them.

- .editorconfig
- sources/TileDB.CSharp/Array.cs
- sources/TileDB.CSharp/ArraySchema.cs
- sources/TileDB.CSharp/ArraySchemaEvolution.cs
- sources/TileDB.CSharp/Attribute.cs
- sources/TileDB.CSharp/Enumeration.cs
- sources/TileDB.CSharp/Marshalling/MarshaledContiguousStringCollection.cs
- sources/TileDB.CSharp/Marshalling/MarshaledString.cs
- sources/TileDB.CSharp/Marshalling/MarshaledStringCollection.cs
- sources/TileDB.CSharp/Marshalling/SafeHandles/EnumerationHandle.cs
- sources/TileDB.CSharp/QueryCondition.cs
- sources/TileDB.CSharp/ThrowHelpers.cs
- tests/TileDB.CSharp.Test/EnumerationTest.cs
[SC-30204](https://app.shortcut.com/tiledb-inc/story/30204/csharp-support-for-enumerated-types)
> Add support for enumerations.

- tests/TileDB.CSharp.Test/DeletesTest.cs
[SC-38119](https://app.shortcut.com/tiledb-inc/story/38119/dropping-an-attribute-seemingly-has-no-effect)
TileDB-Inc/TileDB#4549 fixed array time travelling to honor the starting and ending timestamps when opening the schema.
In the test the array's timestamp had been set by a previous call to `TestUtil.ReadArray` in a range that excluded the remaining attribute.
This PR resets the timestamp range before writing the array schema. The test has been verified to be fixed on my machine.
Fixes #334
Fixes #335
Fixes #337
> Fix schema evolution delete test.

- .github/workflows/nightly.yml
Because building the Core and running the C# tests happens on separate jobs, they might run on a different machine. If the building machine supports AVX2 and the testing machine does not, the latter will fail with an invalid opcode error.
This is my latest theory on why the macOS nightly builds often fail, especially since nightly builds on other TileDB projects also fail on macOS. With this PR we always disable AVX2 when building the Core.
If this PR gets merged and we don't get a related nightly failure for two weeks, I will consider the failures fixed and will close all relevant issues.
> Disable AVX2 on nightly builds.

- .github/workflows/nightly.yml
- .github/workflows/release.yml
Artifacts are now immutable and we can't upload many times to the same one, but what we can do is upload to many artifacts with a common prefix, and download all of them with a pattern.
Validated by [successfully launching a nightly build](https://github.com/teo-tsirpanis/TileDB-CSharp/actions/runs/7561966064).
> Update the download/upload artifact actions to version 4.

- sources/TileDB.CSharp/Marshalling/SafeHandles/QueryHandle.cs
- sources/TileDB.CSharp/Query.cs
- tests/TileDB.CSharp.Test/QueryTest.cs
[SC-39730](https://app.shortcut.com/tiledb-inc/story/39730/query-objects-leak-pinned-gc-handles-if-not-disposed)
To pass query buffers to the Core, the C# API has to pin them to keep them alive and prevent the GC from moving them, and they get unpinned when the query gets `Dispose`d. However, if the user forgets to dispose the query, the buffers do not get unpinned, resulting in a memory leak. The native `tiledb_query_t*` still gets freed because it is managed by a `SafeHandle` which has a finalizer.
This PR fixes this leak by moving the query buffer management logic from `Query` to `QueryHandle`. This means that if the `Query` does not get disposed, its `QueryHandle` will also not get disposed, its finalizer will run and both free the `tiledb_query_t*` and unpin the buffers.
I added a …
> Fix pinned memory leaks if queries are not disposed.

- .github/workflows/nightly.yml
- Directory.Packages.props
- sources/TileDB.CSharp/TileDB.CSharp.csproj
- tests/TileDB.CSharp.Test/TileDB.CSharp.Test.csproj
Since 2.22 did not expose any new C API, no changes to C# code are required.
> Update Core to 2.22

- .github/workflows/nightly.yml
- .github/workflows/tiledb-csharp.yml
- examples/TileDB.CSharp.Example/TileDB.CSharp.Example.csproj
- tests/TileDB.CSharp.Test/TileDB.CSharp.Test.csproj
Fixes nightly builds.
For some backstory, the packaging system of the C# API enables Core patches to be released without any changes to the C# API package. This has the downside that by default the earliest (`.0`) Core patch gets used, which means that to update the Core users have to install the `TileDB.Native` package themselves.
c3f0ace9525cfb401721c032ccaaa6ba74d831e4 tried to make the tests always use the latest Core version, but it caused nightlies to fail because we cannot install floating versions of packages because we have enabled [NuGet Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management). This PR reverts that commit. The `.0` patch will still get used, and I left instructions in the tests for how to run tests with a …
> Revert floating the Core's version in tests and fix CI.

- examples/TileDB.CSharp.Example/ExampleVFS.cs
- examples/TileDB.CSharp.Example/Program.cs
Add VFS list example, with optional config for usage to set S3 or other parameters.
> Add VFS list example, with optional config

- .github/workflows/nightly.yml
Part of [SC-48973](https://app.shortcut.com/tiledb-inc/story/48973/revert-pins-to-msvc-toolset-14-39)
GitHub Actions is starting to update the MSVC toolset version in CI, causing [occasional failures in the Core](https://github.com/TileDB-Inc/TileDB/actions/runs/9386900730/job/25848568717). This PR removes the pin to version 14.39 added in #388.
> Remove pin to MSVC toolset version in nightly builds.

- .github/dependabot.yml
- .github/workflows/docs.yml
- .github/workflows/generate-bindings.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tiledb-csharp.yml
- global.json
Fixes #485.
* The "Remove existing .NET versions" step was removed. It is not necessary because the .NET SDK version to use is pinned by the `global.json` file. ~~Moreover it's likely that the forced deletion of the `$DOTNET_ROOT` folder corrupts the installation and causes nightlies to fail because the `dotnet --info` command fails with an exception.~~
* The .NET SDK used was updated from 8.0.1xx to 8.0.4xx.
> Fix nightlies et al.

- scripts/nuget/GenerateNuGetPackages.proj
Starting with TileDB version 2.27.0 we ship binaries for linux-arm64. This PR updates the NuGet package generation script to pack them as well.
If we need to make a patch release for a pre-2.27 release, we will have to generate the NuGet packages with an earlier version of the script.
> Create native NuGet packages for linux-arm64.

- .github/workflows/nightly.yml
The main branch name in the Core was changed to `dev`.
Fixes #505
> Fix nightlies.

- .github/workflows/docs.yml
- .github/workflows/generate-bindings.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tiledb-csharp.yml
[SC-62651](https://app.shortcut.com/tiledb-inc/story/62651/c-ci-has-been-failing-to-run-dotnet-info-on-windows)
They are not actually needed and have been failing to run on Windows. The .NET SDK version we are using is being set by `global.json` file, and installed by the steps just above.
Fixes #512
> Remove "Display .NET versions" GHA steps.

- .github/workflows/nightly.yml
- .github/workflows/tiledb-csharp.yml
- examples/TileDB.CSharp.Example/TileDB.CSharp.Example.csproj
- sources/TileDB.CSharp/CompatibilitySuppressions.xml
- sources/TileDB.CSharp/TileDB.CSharp.csproj
- tests/TileDB.CSharp.Test/TileDB.CSharp.Test.csproj
[SC-64485](https://app.shortcut.com/tiledb-inc/story/64485/update-target-framework-to-net-8)
Consistent with the [.NET support policy](https://dotnet.microsoft.com/en-us/platform/support/policy), this PR updates the minimum supported target framework of TileDB-CSharp to .NET 8. This will open the door to some substantial improvements down the road. More details in the story.
> Update target framework to .NET 8.

- CONTRIBUTING.md
This used to be in the docs, and we're migrating it into each repo.
> Add Contributor's guide

- .github/workflows/nightly.yml
Fixes #576.
Due to changes in CMake 4.0, we have to explicitly configure `SDKROOT`, like we do in TileDB-Inc/TileDB#5633. We also remove some outdated CMake options, and disable S3, serialization and testing, which are not used by the C# tests.
Validated by [successfully running a nightly build](https://github.com/teo-tsirpanis/TileDB-CSharp/actions/runs/17764976537).
> Configure macOS `SDKROOT` when building native components et al.
